### ISSUE TITLE
client sometimes don't receive server streaming messages

### ISSUE THREAD

**Issue by bbigras** [pingcap/grpc-rs#165]
If I run the following code multiple times, it sometimes don't receive a response. Also I'm not sure why there's always a cancelled error.

**log with response:**
```
     Running `target/debug/grpc-client`
response: value: "test"
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: RpcFailure(RpcStatus { status: Cancelled, details: Some("Cancelled") })', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**log without response:**
```
     Running `target/debug/grpc-client`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: RpcFailure(RpcStatus { status: Cancelled, details: Some("Cancelled") })', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

grpcio 0.2.1
grpcio-proto 0.2.0
same thing with 3110b36c085e1d6dee14189bfe0a894430f66f3c
rustc 1.26.0-nightly (2789b067d 2018-03-06)
Arch Linux

**proto**
```proto
syntax = "proto3";

package testcase;

message Empty {}

service TestCase {
  rpc Sub(Empty) returns (stream Notification) {}
}

message Notification {
  string value = 1;
}
```

**server**
```rust
extern crate futures;
extern crate grpcio;
extern crate grpcio_proto;
extern crate protobuf;

mod testcase;
mod testcase_grpc;

use testcase::{Empty, Notification};
use testcase_grpc::{create_test_case, TestCase};

use futures::sync::oneshot;
use futures::{Future, Sink};
use grpcio::{Environment, RpcContext, ServerBuilder, ServerStreamingSink, WriteFlags};

use std::io::Read;
use std::sync::Arc;
use std::{io, thread};

#[derive(Clone)]
struct TestService;

impl TestCase for TestService {
    fn sub(&self, ctx: RpcContext, _req: Empty, sink: ServerStreamingSink<Notification>) {
        println!("sub");

        let mut n = Notification::new();
        n.set_value("test".to_string());
        let f = sink.send((n, WriteFlags::default()))
            .map(|_sink| ())
            .map_err(|e| panic!(e));

        ctx.spawn(f);
    }
}

fn main() {
    let env = Arc::new(Environment::new(1));
    let service = create_test_case(TestService);
    let mut server = ServerBuilder::new(env)
        .register_service(service)
        .bind("127.0.0.1", 50051)
        .build()
        .unwrap();
    server.start();
    for &(ref host, port) in server.bind_addrs() {
        println!("listening on {}:{}", host, port);
    }
    let (tx, rx) = oneshot::channel();
    thread::spawn(move || {
        println!("Press ENTER to exit...");
        let _ = io::stdin().read(&mut [0]).unwrap();
        tx.send(())
    });
    let _ = rx.wait();
    let _ = server.shutdown().wait();
}
```

**client**
```rust
extern crate futures;
extern crate grpcio;
extern crate grpcio_proto;
extern crate protobuf;

mod testcase;
mod testcase_grpc;

use testcase::Empty;
use testcase_grpc::TestCaseClient;

use futures::{Future, Stream};
use grpcio::{ChannelBuilder, EnvBuilder};

use std::sync::Arc;

fn main() {
    let env = Arc::new(EnvBuilder::new().build());
    let ch = ChannelBuilder::new(env).connect("127.0.0.1:50051");

    let client = TestCaseClient::new(ch);

    let req = Empty::new();
    let stream = client.sub(&req).expect("rpc");

    let t = stream.for_each(|response| {
        println!("response: {:?}", response);
        Ok(())
    });

    t.wait().unwrap();
}
```

**Comment by siddontang** [comment]
PTAL @overvenus

**Comment by BusyJay** [comment]
That's because the sink in server API is not closed. `Cancelled` means the request is aborted. A proper example to handle an rpc call is
```
sink.send(resp).wait().unwrap();
sink.send(resp).wait().unwrap();
...
future::poll_fn(|| sink.close()).wait().unwrap();
```

**Comment by bbigras** [comment]
Thanks. It works if I change my code to the following:
```rust
let f = sink.send((n, WriteFlags::default()))
            .and_then(|mut sink| sink.close())
            .map(|_| ())
            .map_err(|e| panic!(e));
```

I'm still learning how to use futures but would it be possible to close the sink automatically on drop?
