### ISSUE TITLE
Unstable test: empty_stream::test_secure

### ISSUE THREAD

**Issue by nrc** [pingcap/grpc-rs#345]
From https://travis-ci.org/pingcap/grpc-rs/jobs/559681593, `cargo test --features "openssl-vendored" --all`

stack trace:

```
---- empty_stream::test_secure stdout ----
testing empty stream ... thread 'empty_stream::test_secure' panicked at 'called `Result::unwrap()` on an `Err` value: RpcFinished(None)', src/libcore/result.rs:1051:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: rust_begin_unwind
             at src/libstd/panicking.rs:311
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::result::unwrap_failed
             at /rustc/4b65a86ebace8600c8e269e8bfe3365cdc460e68/src/libcore/macros.rs:18
  11: core::result::Result<T,E>::unwrap
             at /rustc/4b65a86ebace8600c8e269e8bfe3365cdc460e68/src/libcore/result.rs:852
  12: interop::client::Client::empty_stream
             at interop/src/client.rs:124
  13: tests::empty_stream::test_secure
             at interop/tests/tests.rs:51
  14: tests::empty_stream::test_secure::{{closure}}
             at interop/tests/tests.rs:21
  15: core::ops::function::FnOnce::call_once
             at /rustc/4b65a86ebace8600c8e269e8bfe3365cdc460e68/src/libcore/ops/function.rs:231
  16: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/4b65a86ebace8600c8e269e8bfe3365cdc460e68/src/liballoc/boxed.rs:766
  17: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:82
  18: std::panicking::try
             at /rustc/4b65a86ebace8600c8e269e8bfe3365cdc460e68/src/libstd/panicking.rs:275
  19: std::panic::catch_unwind
             at /rustc/4b65a86ebace8600c8e269e8bfe3365cdc460e68/src/libstd/panic.rs:394
  20: test::run_test::run_test_inner::{{closure}}
             at src/libtest/lib.rs:1466
```

**Comment by hunterlxt** [comment]
Generally I will choose to restart, it is worth fixing
