### ISSUE TITLE
Seems type `bytes` is not compatible between c++ and rust

### ISSUE THREAD

**Issue by new-commer** [pingcap/grpc-rs#358]
I defined a Blob struct as below 
```protobuf
message UintMessage {
  uint32 len = 1;
}

message Blob {
  bytes  blob= 1;
}
```
And defined a interface as below
```protobuf
service Test {
  rpc transmit(UintMessage ) returns (Blob) {}
}
```
Then i implement server by c++ and client by rust .
Client panic when running it .
I saw `bytes` is `string` in c++ and `vec` in rust . Seems it is not compatible.

**Comment by BusyJay** [comment]
Can you show me the panic messages and stace trace of client? They are binary-compatible, not interface compatible, they are different language after all.

**Comment by new-commer** [comment]
Below is the stack trace of client 
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', src/libcore/result.rs:999:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: rust_begin_unwind
             at src/libstd/panicking.rs:308
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/macros.rs:18
   9: core::result::Result<T,E>::unwrap
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/result.rs:800
  10: bb::run
             at bb/src/main.rs:172
  11: bb::main
             at bb/src/main.rs:189
  12: std::rt::lang_start::{{closure}}
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/rt.rs:64
  13: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  14: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:85
  15: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:394
             at src/libstd/rt.rs:48
  16: std::rt::lang_start
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/rt.rs:64
  17: main
  18: __libc_start_main
  19: <unknown>
```

**Comment by BusyJay** [comment]
Can you also paste the code of main.rs file?

**Comment by new-commer** [comment]
Ah , the error message is ` RpcFailure(RpcStatus { status: Unimplemented, details: Some("") })`

**Comment by new-commer** [comment]
抱歉，只能拷贝一部分代码
```
       let mut request = UintMessage::new();
        request.len = 10;
          self.cli
                .transmit_async(&request)
                .unwrap()
                .map(|_| ()) 
                .map_err(|e| {println!("----error {}", e);error!("{}", e)}),
        )

```

**Comment by new-commer** [comment]
服务端代码
```
        Status transmit(ServerContext* context, const UintMessage* request,
                        Blob * reply) {
                char * buf = new char [request->len()];
                reply->set_blob(buf,lrequest->len());
                return Status::OK;
        }

```
我用c++客户端是可以正常获取数据的

**Comment by BusyJay** [comment]
Can you provide a minimal projects that reproduce the problem? It sounds like a bug.

**Comment by new-commer** [comment]
I'm making a sample , and run into an error when building
```
error[E0425]: cannot find value `VERSION_2_7_0` in module `protobuf`
  --> generated/grpc/src/grpc.rs:27:49
   |
27 | const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_7_0;
   |                                                 ^^^^^^^^^^^^^ help: a constant with a similar name exists: `VERSION_2_8_0`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0425`.
error: Could not compile `grpc_proto`.
``

**Comment by new-commer** [comment]
It works now  , maybe i make something wrong
