### ISSUE TITLE
Call `send` + `close` on `StreamingCallSink` will panic

### ISSUE THREAD

**Issue by hicqu** [pingcap/grpc-rs#93]
Here is a simple [test](https://github.com/hicqu/pb-learn) for learning grpc. We can use `cargo run --bin server` to run the server side, and `cargo run --bin client` to run the client side.

The client side will panic. Here is a code fragment:
```rust
    for i in 0..4 {
        let mut req = req.clone();
        req.set_message(format!("msg_{}", i));
        match sender.send((req, WriteFlags::default())).wait() {
            Ok(s) => sender = s,
            Err(e) => {
                println!("sender.send: {}", e);
                process::exit(0);
            }
        }
    }
    if let Err(e) = sender.close() {    // panic will happend here.
        println!("sender.close: {}", e);
        process::exit(0);
    }
```

panic stack backtrace:
```
thread 'main' panicked at 'no Task is currently running', /home/qupeng/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.16/src/task_impl/mod.rs:44:8
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:611
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:572
   6: futures::task_impl::with
             at /home/qupeng/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.16/src/task_impl/mod.rs:44
   7: futures::task_impl::current
             at /home/qupeng/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.16/src/task_impl/mod.rs:90
   8: <grpcio::async::CqFuture<T> as futures::future::Future>::poll
             at /home/qupeng/.cargo/registry/src/github.com-1ecc6299db9ec823/grpcio-0.1.0/src/async/mod.rs:113
   9: <grpcio::call::client::StreamingCallSink<P> as futures::sink::Sink>::close
             at /home/qupeng/.cargo/registry/src/github.com-1ecc6299db9ec823/grpcio-0.1.0/src/call/client.rs:309
  10: client::test_cstream_sync
             at src/client/main.rs:70
  11: client::main
             at src/client/main.rs:98
  12: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:99
  13: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:61
  14: main
  15: __libc_start_main
  16: _start
```

**Comment by BusyJay** [comment]
This is the expected behavior, see [documentation of sink](https://docs.rs/futures/0.1.16/futures/sink/trait.Sink.html#method.close) for details. You can also see [examples](https://github.com/pingcap/grpc-rs/tree/master/examples) and [integration tests](https://github.com/pingcap/grpc-rs/tree/master/interop) for how to use grpcio (correctly).

**Comment by hicqu** [comment]
The last problem is resolve perfect, thanks.
But how about this:
```rust
fn test_cstream_sync_1(client: &DebugClient) {
    let req = GetRequest::new();
    let (sender, receiver) = client.cstream();
    let mut waiter = sender.wait();
    for i in 0..4 {
        let mut req = req.clone();
        req.set_message(format!("msg_{}", i));
        if let Err(e) = waiter.send((req, WriteFlags::default())) {
            println!("sender.send: {}", e);
            process::exit(0);
        }
    }
    waiter.flush().unwrap();    // how can the waiter tell the server side the stream is finished?
    drop(waiter);
    match receiver.wait() {
        Ok(resp) => println!("resp message: {}", resp.get_message()),
        Err(e) => println!("receiver.wait: {}", e),
    }
}
```
When I test this code, the client side will block forever because the server side doesn't know the stream is over, so it won't write response back.

**Comment by BusyJay** [comment]
You need to close `waiter` instead of dropping it.

**Comment by hicqu** [comment]
Got it, I will test that feature in master branch of futures-rs. Thanks.
